export const createCoreModuleSource = () => [
  'const getEnvironmentFile = (name: string) => {',
  '  const file = process.env[name]',
  '  if (!file) {',
  '    throw new Error(\`Missing \${name}.\`)',
  '  }',
  '  return file',
  '}',
  '',
  'const toCommandValue = (value: unknown) => {',
  '  if (value === undefined || value === null) {',
  "    return ''",
  '  }',
  "  if (typeof value === 'string') {",
  '    return value',
  '  }',
  '  const serialized = JSON.stringify(value)',
  "  return serialized === undefined ? '' : serialized",
  '}',
  '',
  String.raw`const escapeCommandValue = (value: unknown) => toCommandValue(value).replaceAll('%', '%25').replaceAll('\r', '%0D').replaceAll('\n', '%0A')`,
  "const escapeCommandProperty = (value: unknown) => escapeCommandValue(value).replaceAll(':', '%3A').replaceAll(',', '%2C')",
  '',
  'const toCommandPropertyString = (properties?: Record<string, unknown>) => {',
  '  if (!properties) {',
  "    return ''",
  '  }',
  "  const entries = Object.entries(properties).filter(([, value]) => value !== undefined && value !== null && value !== '')",
  '  if (!entries.length) {',
  "    return ''",
  '  }',
  "  return ' ' + entries.map(([key, value]) => \`\${key}=\${escapeCommandProperty(value)}\`).join(',')",
  '}',
  '',
  "const issueCommand = (command: string, message = '', properties?: Record<string, unknown>) => {",
  '  console.log(\`::\${command}\${toCommandPropertyString(properties)}::\${escapeCommandValue(message)}\`)',
  '}',
  '',
  'const appendEnvironmentFileValue = (environmentFileName: string, name: string, value: unknown) => {',
  '  const stringValue = toCommandValue(value)',
  "  const delimiter = 'gha_delimiter_' + crypto.randomUUID()",
  String.raw`  const serializedLine = /[\r\n]/.test(stringValue)`,
  '    ? \`\${name}<<\${delimiter}\\n\${stringValue}\\n\${delimiter}\\n\`',
  '    : \`\${name}=\${stringValue}\\n\`',
  "  appendFileSync(getEnvironmentFile(environmentFileName), serializedLine, 'utf8')",
  '}',
  '',
  'const appendEnvironmentFileLine = (environmentFileName: string, value: unknown) => {',
  "  appendFileSync(getEnvironmentFile(environmentFileName), \`\${toCommandValue(value)}\\n\`, 'utf8')",
  '}',
  '',
  'const summary = {',
  '  append(value: unknown) {',
  "    appendFileSync(getEnvironmentFile('GITHUB_STEP_SUMMARY'), toCommandValue(value), 'utf8')",
  '  },',
  '  clear() {',
  "    writeFileSync(getEnvironmentFile('GITHUB_STEP_SUMMARY'), '', 'utf8')",
  '  },',
  '  write(value: unknown) {',
  "    writeFileSync(getEnvironmentFile('GITHUB_STEP_SUMMARY'), toCommandValue(value), 'utf8')",
  '  },',
  '}',
  '',
  'export const core = {',
  '  addPath(inputPath: unknown) {',
  "    appendEnvironmentFileLine('GITHUB_PATH', inputPath)",
  '  },',
  '  debug(message: unknown) {',
  "    issueCommand('debug', message)",
  '  },',
  '  endGroup() {',
  "    issueCommand('endgroup')",
  '  },',
  '  error(message: unknown, properties?: Record<string, unknown>) {',
  "    issueCommand('error', message, properties)",
  '  },',
  '  exportVariable(name: string, value: unknown) {',
  "    appendEnvironmentFileValue('GITHUB_ENV', name, value)",
  '  },',
  '  getState(name: string) {',
  "    return process.env['STATE_' + name] || ''",
  '  },',
  '  async group<Value>(name: unknown, callback: () => Value | Promise<Value>) {',
  '    this.startGroup(name)',
  '    try {',
  '      return await callback()',
  '    } finally {',
  '      this.endGroup()',
  '    }',
  '  },',
  '  info(message: unknown) {',
  '    console.log(toCommandValue(message))',
  '  },',
  '  isDebug() {',
  "    return process.env.RUNNER_DEBUG === '1'",
  '  },',
  '  notice(message: unknown, properties?: Record<string, unknown>) {',
  "    issueCommand('notice', message, properties)",
  '  },',
  '  saveState(name: string, value: unknown) {',
  "    appendEnvironmentFileValue('GITHUB_STATE', name, value)",
  '  },',
  '  setFailed(message: unknown) {',
  '    const normalizedMessage = message instanceof Error ? message.stack || message.message : message',
  "    issueCommand('error', normalizedMessage)",
  '    process.exitCode = 1',
  '  },',
  '  setOutput(name: string, value: unknown) {',
  "    appendEnvironmentFileValue('GITHUB_OUTPUT', name, value)",
  '  },',
  '  setSecret(secret: unknown) {',
  "    issueCommand('add-mask', secret)",
  '  },',
  '  startGroup(name: unknown) {',
  "    issueCommand('group', name)",
  '  },',
  '  summary,',
  '  warning(message: unknown, properties?: Record<string, unknown>) {',
  "    issueCommand('warning', message, properties)",
  '  },',
  '}',
].join('\n')
