export const ACTION_RUN_TYPESCRIPT_INTERNAL_MODE = 'ACTION_RUN_TYPESCRIPT_INTERNAL_MODE'
export const ACTION_RUN_TYPESCRIPT_INTERNAL_BINDINGS = 'ACTION_RUN_TYPESCRIPT_INTERNAL_BINDINGS'
export const ACTION_RUN_TYPESCRIPT_INTERNAL_CODE = 'ACTION_RUN_TYPESCRIPT_INTERNAL_CODE'

export const internalEnvironmentNames = [
  ACTION_RUN_TYPESCRIPT_INTERNAL_MODE,
  ACTION_RUN_TYPESCRIPT_INTERNAL_BINDINGS,
  ACTION_RUN_TYPESCRIPT_INTERNAL_CODE,
] as const
